//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxie_MVC_Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class lstFeeType
    {
        public lstFeeType()
        {
            this.tblItemCost = new HashSet<tblItemCost>();
        }
    
        public int FeeTypeID { get; set; }
        public string FeeTypeCode { get; set; }
        public string FeeTypeDescription1 { get; set; }
        public string FeeTypeDescription2 { get; set; }
        public string FeeTypeDescription3 { get; set; }
    
        public virtual ICollection<tblItemCost> tblItemCost { get; set; }
    }
}
