//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxie_MVC_Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class lstSourceCode
    {
        public string SourceCode { get; set; }
        public string SourceCodeDescription1 { get; set; }
        public string SourceCodeDescription2 { get; set; }
        public string SourceCodeDescription3 { get; set; }
        public bool Changeble { get; set; }
    }
}
