//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxie_MVC_Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemPrice
    {
        public int ItemPriceID { get; set; }
        public int ItemID { get; set; }
        public string StoreCode { get; set; }
        public Nullable<int> PriceSourceCode { get; set; }
        public Nullable<double> PriceValue { get; set; }
        public Nullable<double> PriceQty { get; set; }
        public Nullable<System.DateTime> PriceStart { get; set; }
        public Nullable<System.DateTime> PriceStop { get; set; }
        public Nullable<System.DateTime> ItemDateAdd { get; set; }
        public Nullable<System.DateTime> ItemDateChg { get; set; }
    
        public virtual tblItem tblItem { get; set; }
    }
}
