//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxie_MVC_Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemDetail
    {
        public int ItemDetailID { get; set; }
        public int ItemID { get; set; }
        public int StoreCode { get; set; }
        public int TaxGrpCode { get; set; }
        public Nullable<int> BtlCode { get; set; }
        public Nullable<int> EnvCode { get; set; }
        public Nullable<int> TareCode { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string ItemDescription1 { get; set; }
        public string ItemDescription2 { get; set; }
        public string ItemDescription3 { get; set; }
        public Nullable<System.DateTime> ItemDateAdd { get; set; }
        public Nullable<System.DateTime> ItemDateChg { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblTaxGrp tblTaxGrp { get; set; }
    }
}
