//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxie_MVC_Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemPriceDetail
    {
        public int ItemPriceDetailID { get; set; }
        public int ItemID { get; set; }
        public int StoreCode { get; set; }
        public int PriceSourceCode { get; set; }
        public double PriceValue { get; set; }
        public double PriceQty { get; set; }
        public System.DateTime PriceStart { get; set; }
        public System.DateTime PriceStop { get; set; }
        public Nullable<System.DateTime> ItemDateAdd { get; set; }
        public Nullable<System.DateTime> ItemDateChg { get; set; }
    
        public virtual tblItem tblItem { get; set; }
    }
}
