//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxie_MVC_Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemCost
    {
        public int ItemCostID { get; set; }
        public int ItemID { get; set; }
        public int StoreCode { get; set; }
        public Nullable<double> CostValue { get; set; }
        public Nullable<double> CostQty { get; set; }
        public string VendorCode { get; set; }
        public string VendorSKU { get; set; }
        public string VendorFormat { get; set; }
        public Nullable<double> FeesValue { get; set; }
        public string FeeTypeCode { get; set; }
        public Nullable<System.DateTime> CostStart { get; set; }
        public Nullable<System.DateTime> CostStop { get; set; }
        public Nullable<System.DateTime> ItemDateAdd { get; set; }
        public Nullable<System.DateTime> ItemDateChg { get; set; }
    
        public virtual lstFeeType lstFeeType { get; set; }
        public virtual tblItem tblItem { get; set; }
    }
}
