//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxie_MVC_Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxGrp
    {
        public tblTaxGrp()
        {
            this.tblItemDetail = new HashSet<tblItemDetail>();
            this.tblTax = new HashSet<tblTax>();
        }
    
        public int TaxGrpID { get; set; }
        public int TaxGrpCode { get; set; }
        public string TaxGrpDescription1 { get; set; }
        public string TaxGrpDescription2 { get; set; }
        public string TaxGrpDescription3 { get; set; }
    
        public virtual ICollection<tblItemDetail> tblItemDetail { get; set; }
        public virtual ICollection<tblTax> tblTax { get; set; }
    }
}
