//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxie_MVC_Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTax
    {
        public tblTax()
        {
            this.tblTaxGrp = new HashSet<tblTaxGrp>();
        }
    
        public int TaxID { get; set; }
        public int TaxCode { get; set; }
        public string TaxDescription1 { get; set; }
        public string TaxDescription2 { get; set; }
        public string TaxDescription3 { get; set; }
        public double TaxValue { get; set; }
        public double TaxRoundValue { get; set; }
        public double TaxStartValue { get; set; }
        public Nullable<bool> TaxAtCode { get; set; }
        public Nullable<bool> TaxLineFlag { get; set; }
    
        public virtual ICollection<tblTaxGrp> tblTaxGrp { get; set; }
    }
}
